### ISSUE TITLE
既然是wine，为什么不用高版本的qq呢

### ISSUE THREAD

**Issue by Neutree** [ZQiang94/ubuntu-QQ#1]
# 既然是wine，为什么不用高版本的qq呢

有试过高版本的么

**Comment by ZQiang94** [comment]
![image](https://cloud.githubusercontent.com/assets/7663942/14521097/51083578-025a-11e6-94aa-0eb9265f00f5.png)
这个就是最新更新的版本，但是还是2012版的。
http://www.ubuntukylin.com/application/这是应用商店
