### ISSUE TITLE
需要二维码验证。。。但是没显示二维码

### ISSUE THREAD

**Issue by Neutree** [ZQiang94/ubuntu-QQ#2]
需要二维码验证。。。但是没显示二维码。。。。。。。。。。。。
![2016-04-28 22 17 18](https://cloud.githubusercontent.com/assets/8625829/14888939/21282ef4-0d8f-11e6-9887-d2bf606bef50.png)

**Comment by ZQiang94** [comment]
先把设备锁关掉，再重新试一遍。

**Comment by Neutree** [comment]
可以了，谢啦
